backend:
  name: github
  repo: bhnywl/personal-site

media_folder: static/assets
public_folder: /assets

collections:
  - name: posts
    label: Posts
    folder: cms/posts
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: image, label: Image, widget: image }
      - { name: body, label: Body, widget: markdown }

  - name: projects
    label: Projects
    folder: cms/projects
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: githubUrl, label: Github Url, required: false }
      - { name: title, label: Title }
      - { name: image, label: Image, widget: image }
      - { name: description, label: Description }
      - { name: order, label: Order, widget: number }
      - { name: tech, label: Tech, widget: list, field: {
          name: techType, label: Tech Type, widget: "select", options: [
            "React", "Redux", "Ruby on Rails", "JavaScript", "Ruby", "Gatsby", "Webpack", "Sass", "GraphQL"
          ]
        } }
