backend:
  name: github
  repo: bhnywl/personal-site

media_folder: static/assets

collections:
  - name: blog
    label: Blog
    folder: blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: thumbnail, label: Thumbnail, widget: image }
      - { name: image, label: Image, widget: image }
      - { name: tags, label: Tags, widget: list }
